#!/bin/bash

# Script to generate serverless.ts from functions folder
FUNCTIONS_DIR="functions"
BUILD_DIR="build-function"
OUTPUT_FILE="serverless.ts"

# Create build directory
mkdir -p "$BUILD_DIR"

# Clear build directory
rm -f "$BUILD_DIR"/*.ts

# Process each function file - transform and copy to build-function
for func_file in "$FUNCTIONS_DIR"/*.ts; do
  if [ -f "$func_file" ]; then
    func_name=$(basename "$func_file" .ts)
    output_file="$BUILD_DIR/$func_name.ts"
    
    echo "Processing $func_file -> $output_file"
    
    # Transform the function:
    # 1. Replace "Deno.serve(async (req) => {" with "export const functionName = async (req: Request) => {"
    # 2. Replace the last "});" at the end with "};"
    # 3. Replace base44 SDK import with custom SDK
    sed -e "s/^Deno\.serve(async (req) => {$/export const $func_name = async (req: Request) => {/" \
        -e '$s/^});$/};/' \
        -e "s|from 'npm:@base44/sdk@0.8.4'|from '../src/sdk/function-sdk.ts'|" \
        "$func_file" > "$output_file"
  fi
done

# Generate serverless.ts
cat > "$OUTPUT_FILE" << 'EOF'
// serverless.ts
// Auto-generated by serverless-build.sh
EOF

# Add imports - import directly from build-function folder
for func_file in "$FUNCTIONS_DIR"/*.ts; do
  if [ -f "$func_file" ]; then
    func_name=$(basename "$func_file" .ts)
    echo "import { $func_name } from './build-function/$func_name.ts';" >> "$OUTPUT_FILE"
  fi
done

# Add router
cat >> "$OUTPUT_FILE" << 'EOF'

Deno.serve({ port: 8000 }, async (req: Request) => {
  const url = new URL(req.url);

  // Router đơn giản dựa trên path
  switch (url.pathname) {
    case '':
    case '/':
      return new Response(JSON.stringify({ success: true }), {
        status: 200,
        headers: { 'Content-Type': 'application/json' },
      });
EOF

# Add routes
for func_file in "$FUNCTIONS_DIR"/*.ts; do
  if [ -f "$func_file" ]; then
    func_name=$(basename "$func_file" .ts)
    route_path="/$func_name"
    echo "    case '$route_path':" >> "$OUTPUT_FILE"
    echo "      return await $func_name(req);" >> "$OUTPUT_FILE"
  fi
done

# Close router
cat >> "$OUTPUT_FILE" << 'EOF'
    default:
      return new Response(JSON.stringify({ error: 'Not Found' }), {
        status: 404,
        headers: { 'Content-Type': 'application/json' },
      });
  }
});
EOF

echo "Generated $OUTPUT_FILE successfully"

